### PR TITLE
Add VPR score (if available) to ticket details

### LINKED ISSUE #61: Store VPR information when available from VS scans
# Summary #

Moving forward, CyHy requests that we store the [VPR Vulnerability Priority Rating](https://docs.tenable.com/tenablesc/Content/RiskMetrics.htm#Vulnerability-Priority-Rating-) scores when included as associated data in any Nessus scan results. 

## Motivation and context ##

- We should account for possible empty values given not all CVEs will have a VPR score.
- This score will be a number between 0.1-10.0 (9.0-10.0=critical as scoring is loosely based on CVSS).
- VPR may be included prior to NVD-publishing based on disclosure publications.
- This information may be incorporated into the vuln_scan collection’s data (similar to the other fields that come back from Nessus). 

This change is required to support [Modify CyHy VS to include CVSSv3+ and VPR scoring #59](https://github.com/cisagov/cyhy-system/issues/59)

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR adds the [Vulnerability Priority Rating (VPR)](https://docs.tenable.com/tenablesc/Content/RiskMetrics.htm#Vulnerability-Priority-Rating-) score to the CyHy ticket details, if the VPR score is present in the vulnerability scan document.

## 💭 Motivation and context ##

This is part of the work for https://github.com/cisagov/cyhy-system/issues/59.

Note that the VPR score is only available from [Nessus 8.14.0](https://docs.tenable.com/releasenotes/Content/nessus/nessus8140.htm) or later.

* Resolves https://github.com/cisagov/cyhy-system/issues/61.

## 🧪 Testing ##

To test this, I deployed this code to my test environment (which includes a vulnscan instance running Nessus 8.15.4) and re-ran vulnerability scans for some vulnerable hosts.  I verified that when the scans completed, all of the updated tickets included the new `details.vpr_score` field, as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
image

**Review by felddy — COMMENTED** [review]
I don't like this idea. 👎 

VPR: https://www.tenable.com/blog/what-is-vpr-and-how-is-it-different-from-cvss

1. This is runs against the concept that we do not allow private companies dictate the work priorities of federal agencies. 
1. It is duplicative of our wonderful BOD 22-01 work. 
1. It will most likely lead to confusion.
1. CyHy is supposed to be sensor agnostic.  Once Nessus goes away so will this field.

**Comment by dav3r** [comment]
> I don't like this idea. 👎

@felddy Can you please work this out with the CyHy team and let me know what happens so that I can resolve this conversation and determine the fate of this PR?

**Comment by dav3r** [comment]
This PR is blocked until @climber-girl lets us know if we want the VPR score to be included in `ticket` documents or if it's sufficient to live only in `vuln_scan` documents while the CyHy team analyzes this data.

**Comment by climber-girl** [comment]
Hi @dav3r! If it isn't too hard to list in the tickets, that would be preferable so we can easily cross compare the CVSS/Tenable Severity and KEV with the VPR score as well :)

**Comment by dav3r** [comment]
> Hi @dav3r! If it isn't too hard to list in the tickets, that would be preferable so we can easily cross compare the CVSS/Tenable Severity and KEV with the VPR score as well :)

Thanks for the quick reply!  I will unblock this PR and we can deploy this code at our next opportunity.

**Review by mcdonnnj — APPROVED** [review]
It does some stuff 😲

**Pull request merged**
